import {useEffect,useState} from 'react';
import {useQuery,useQueryClient} from '@tanstack/react-query';
import {supabase} from '@/integrations/supabase/client';
import {useOrgContext} from '@/hooks/useOrgContext';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Button} from '@/components/ui/button';
import {toast} from 'sonner';
export default function EmployeeSetupCard({employeeId}:{employeeId:string}) {
 const {data:ctx}=useOrgContext();const qc=useQueryClient();const [saving,setSaving]=useState(false);
 const [form,setForm]=useState({hire:'',real:'',cap:'40',max:'100',negative:false,snapshotDate:'',balance:''});
 const {data,error}=useQuery({queryKey:['employee-setup',employeeId],enabled:!!ctx,queryFn:async()=>{
  const [employee,pto,snapshot]=await Promise.all([supabase.from('employees').select('*').eq('id',employeeId).eq('org_id',ctx!.org_id).single(),supabase.from('pto_settings').select('*').eq('employee_id',employeeId).eq('org_id',ctx!.org_id).maybeSingle(),supabase.from('pto_snapshots').select('*').eq('employee_id',employeeId).eq('org_id',ctx!.org_id).order('snapshot_date',{ascending:false}).limit(1).maybeSingle()]);
  if(employee.error)throw employee.error;if(pto.error)throw pto.error;if(snapshot.error)throw snapshot.error;return {employee:employee.data,pto:pto.data,snapshot:snapshot.data};
 }});
 useEffect(()=>{if(data)setForm({hire:data.employee.hire_date??'',real:data.employee.real_hire_date??'',cap:String(data.pto?.worked_hours_cap_weekly??40),max:String(data.pto?.max_balance??100),negative:data.pto?.allow_negative??false,snapshotDate:data.snapshot?.snapshot_date??'',balance:data.snapshot?String(data.snapshot.snapshot_balance_hours):''});},[data]);
 const save=async()=>{if(!ctx||!data)return;const cap=Number(form.cap),max=Number(form.max);if(!form.hire||!form.cap.trim()||!form.max.trim()||!Number.isFinite(cap)||!Number.isFinite(max)||cap<0||max<0){toast.error('Enter a provisional start date and nonnegative PTO limits.');return;}if((!!form.snapshotDate)!==(!!form.balance.trim())||(form.balance.trim()&&!Number.isFinite(Number(form.balance)))){toast.error('Enter both a confirmed PTO balance and its date, or leave both blank.');return;}setSaving(true);
  try{const e=await supabase.from('employees').update({hire_date:form.hire,real_hire_date:form.real||null}).eq('id',employeeId).eq('org_id',ctx.org_id);if(e.error)throw e.error;
   const p=await supabase.from('pto_settings').upsert({org_id:ctx.org_id,employee_id:employeeId,user_id:data.employee.user_id,hire_date:form.hire,worked_hours_cap_weekly:cap,max_balance:max,allow_negative:form.negative,timezone:data.employee.timezone||'America/New_York'},{onConflict:'employee_id'});if(p.error)throw p.error;
   if(form.snapshotDate&&form.balance.trim()){const snap=await supabase.from('pto_snapshots').upsert({org_id:ctx.org_id,employee_id:employeeId,user_id:data.employee.user_id,snapshot_date:form.snapshotDate,snapshot_balance_hours:Number(form.balance)},{onConflict:'employee_id,snapshot_date'});if(snap.error)throw snap.error;}
   await Promise.all([qc.invalidateQueries({queryKey:['pto-snapshots']}),qc.invalidateQueries({queryKey:['employee-setup',employeeId]}),qc.invalidateQueries({queryKey:['org-employees']}),qc.invalidateQueries({queryKey:['employee-detail',employeeId]}),qc.invalidateQueries({queryKey:['pto-settings']})]);toast.success('Employee dates and PTO policy saved.');
  }catch(e){toast.error(e instanceof Error?e.message:'Could not save employee settings.');}finally{setSaving(false);}
 };
 if(error)return <p role="alert" className="text-sm">Employee settings could not be loaded.</p>;
 if(!data)return <p className="text-sm">Loading employee settings…</p>;
 return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor={`hire-${employeeId}`}>Provisional start / PTO start</Label><Input id={`hire-${employeeId}`} type="date" value={form.hire} onChange={e=>setForm({...form,hire:e.target.value})}/></div><div><Label htmlFor={`real-${employeeId}`}>Real start date</Label><Input id={`real-${employeeId}`} type="date" value={form.real} onChange={e=>setForm({...form,real:e.target.value})}/></div></div><p className="text-xs text-muted-foreground">Leave the real start date blank until confirmed. Owners and managers receive in-app reminders about 30 days before, 7 days before, and on 1-, 5-, 10-, 15-, and 20-year anniversaries. The provisional date never triggers an anniversary.</p><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor={`cap-${employeeId}`}>Weekly worked-hours cap for PTO accrual</Label><Input id={`cap-${employeeId}`} type="number" min="0" step="0.01" value={form.cap} onChange={e=>setForm({...form,cap:e.target.value})}/></div><div><Label htmlFor={`max-${employeeId}`}>Maximum PTO balance (hours)</Label><Input id={`max-${employeeId}`} type="number" min="0" step="0.01" value={form.max} onChange={e=>setForm({...form,max:e.target.value})}/></div></div><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor={`snapshot-${employeeId}`}>Confirmed PTO balance date</Label><Input id={`snapshot-${employeeId}`} type="date" value={form.snapshotDate} onChange={e=>setForm({...form,snapshotDate:e.target.value})}/></div><div><Label htmlFor={`balance-${employeeId}`}>Confirmed starting PTO balance (hours)</Label><Input id={`balance-${employeeId}`} type="number" step="0.01" value={form.balance} onChange={e=>setForm({...form,balance:e.target.value})}/></div></div><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.negative} onChange={e=>setForm({...form,negative:e.target.checked})}/>Allow a negative PTO balance</label>{!data.pto&&<p className="text-xs text-muted-foreground">The displayed PTO limits are the app defaults until you save this employee’s policy. No starting PTO balance has been inferred.</p>}<Button disabled={saving} onClick={save}>{saving?'Saving…':'Save dates and PTO policy'}</Button></div>;
}
