import { activityRate, labels } from '@/lib/fill-the-schedule';
import type { ActivityType, Campaign } from '@/lib/fill-the-schedule';
import { Panel } from './ui';
export function Rules({ c }: { c: Campaign }) {
  return <div className="space-y-5"><Panel title="What earns points" subtitle="Team records the actions on the left. The manager handles verification and the items in the second table.">
    <h3 className="mb-3 font-medium">Team records</h3><div className="relative min-w-0 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b"><tr><th className="py-3 pr-4">Completed action</th><th className="py-3 pr-4">Points</th><th className="py-3">How it counts</th></tr></thead><tbody className="divide-y">{(['qr_card', 'unscheduled_booking', 'operative_handoff', 'chairside_card'] as ActivityType[]).map(k => <tr key={k}><td className="py-3 pr-4">{labels[k]}</td><td className="py-3 pr-4">{activityRate(k, c, null) ?? <span className="text-red-700 dark:text-red-300">Setup: not set</span>}</td><td className="py-3">{k === 'qr_card' ? 'Honor system; counts right away' : k === 'chairside_card' && c.pts_chairside_card == null ? 'Report now; approval blocked until rate is set' : 'Manager verifies first'}</td></tr>)}</tbody></table></div>
    <h3 className="mb-3 mt-6 font-medium">Manager verifies and records</h3><div className="relative min-w-0 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b"><tr><th className="py-3 pr-4">Action</th><th className="py-3 pr-4">Points</th><th className="py-3">Requirement</th></tr></thead><tbody className="divide-y"><tr><td className="py-3 pr-4">Documented unscheduled treatment calls</td><td className="py-3 pr-4">{c.pts_call} each</td><td className="py-3">Same-day MaxAssist note and phone code; manager saves the verified weekly total</td></tr><tr><td className="py-3 pr-4">Posted Google review that names you</td><td className="py-3 pr-4">Doctor {c.pts_review_doctor}<br />Hygienist {c.pts_review_hygienist}<br />Clerical {c.pts_review_clerical}<br />Assistant {c.pts_review_assistant}</td><td className="py-3">Actual posted review; manager verifies; confirmed scoring group required</td></tr><tr><td className="py-3 pr-4">Booked appointment attended</td><td className="py-3 pr-4">+{c.pts_attend_bonus}</td><td className="py-3">Linked to an approved unscheduled-list booking; once per original action</td></tr><tr><td className="py-3 pr-4">Prepayment confirmed</td><td className="py-3 pr-4">+{c.pts_prepay_bonus}</td><td className="py-3">Linked to an approved booking or operative handoff; once per original action; card on file is not prepayment</td></tr><tr><td className="py-3 pr-4">On time for huddle</td><td className="py-3 pr-4">{c.pts_huddle} per date</td><td className="py-3">Manager checks attendance; no team tally needed</td></tr></tbody></table></div>
  </Panel><Panel title="Prize picks, weekly tally, and office goal"><ul className="list-disc space-y-3 pl-5 text-sm leading-relaxed"><li>A prize pick is one item from the prize bin. {c.prize_tier1_points} approved points earns one pick; {c.prize_tier2_points} earns two. Maximum two per week. Pending reports do not count.</li><li>Clerical team members need at least {c.clerical_min_calls} verified calls each week to qualify. A scoring group must be set for every prize recipient.</li><li>Points are tallied Friday at noon Eastern time. Actions at or after noon Friday roll into the next tally week. The final partial tally includes actions through December 31. Bonuses count in the week the bonus action happened.</li><li>The highest eligible weekly total picks first. Tied totals share priority. Picks happen Friday or the following Monday afternoon; the manager marks items as received.</li><li>The prize bin includes small prizes and gift cards, with a few bigger surprises. The highest quarter total wins ${c.grand_prize_dollars}; tied quarter leaders are shown for the manager to resolve.</li><li>Office goal: doctor open time under {c.open_hours_goal} hours per week. Actual hours are entered by the manager; missing data is shown as “Not recorded.”</li><li>Approved points are preserved at the rate in effect when awarded. Corrections are logged. If a correction reduces eligibility after prizes were received, the manager sees the discrepancy.</li></ul></Panel></div>;
}
