import { useEffect, useState } from 'react';
import { activityRate, campaignWeeks, labels, localDateTime, officeTimestamp, roles, score, tallyClosed } from '@/lib/fill-the-schedule';
import type { ActivityType, Campaign, Ledger } from '@/lib/fill-the-schedule';
import { Panel, Field, TimeField, TeamSelect, input, button, secondary, nameOf, type Writer } from './ui';
export function Settings({ d, writer }: { d: Ledger; writer: Writer }) {
  const [cardPoints, setCardPoints] = useState(d.campaign.pts_chairside_card == null ? '' : String(d.campaign.pts_chairside_card));
  return <div className="space-y-5"><Panel title="Confirm scoring groups" subtitle="These groups control Google review points and the clerical call minimum. They do not change Purple Envelope permissions or employee job assignments. Existing roster members are included; no invitations are sent.">
    <div className="divide-y">{d.participants.map(p => <div className="flex flex-wrap items-center gap-3 py-3" key={p.id}><div className="min-w-40 flex-1"><p className="text-sm font-medium">{nameOf(d, p.employee_id)}</p>{!p.scoring_role && <p className="text-xs text-red-700 dark:text-red-300">Setup: confirm this group for review points and prizes</p>}</div><label className="w-44"><span className="sr-only">Scoring group for {nameOf(d, p.employee_id)}</span><select className={input} disabled={writer.busy} value={p.scoring_role ?? ''} onChange={e => void writer.write('fts_set_scoring_role', { p_campaign_id: d.campaign.id, p_employee_id: p.employee_id, p_role: e.target.value || null, p_active: p.active }, 'Scoring group updated. Previously awarded review points stay unchanged.')}><option value="">Not confirmed</option>{Object.entries(roles).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={p.active} disabled={writer.busy} onChange={e => void writer.write('fts_set_scoring_role', { p_campaign_id: d.campaign.id, p_employee_id: p.employee_id, p_role: p.scoring_role, p_active: e.target.checked }, 'Campaign participation updated.')} />Participating</label></div>)}</div>
  </Panel><Panel title="Chairside card point rate" subtitle="The case threshold is over $10,000. The point value was not confirmed, so it stays unset until you set it here. This does not award the prepayment bonus."><form className="max-w-md space-y-4" onSubmit={e => { e.preventDefault(); void writer.write('fts_set_rate', { p_campaign_id: d.campaign.id, p_key: 'pts_chairside_card', p_value: cardPoints === '' ? null : Number(cardPoints) }, 'Chairside card point rate saved. Approved points stay unchanged.'); }}>{d.campaign.pts_chairside_card == null && <p className="text-sm text-red-700 dark:text-red-300">Setup needed: the chairside point value is not set.</p>}<Field title="Points per verified chairside card presentation"><input className={input} type="number" min="0" max="100" step="1" placeholder="Not set" value={cardPoints} onChange={e => setCardPoints(e.target.value)} /></Field><button className={button} disabled={writer.busy}>Save point rate</button><p className="text-xs text-muted-foreground">Leave blank to keep approvals blocked. Already-awarded points are never rewritten.</p></form></Panel>
    <Panel title="Recent change history" subtitle="Manager-only history of reports, verification, corrections, and settings."><ul className="divide-y text-sm">{d.audit.slice().sort((a, b) => b.created_at.localeCompare(a.created_at)).slice(0, 25).map(a => <li className="py-3" key={a.id}><p>{a.employee_id ? nameOf(d, a.employee_id) : 'Campaign'} · {a.entity.replace(/_/g, ' ')} · {a.action.replace(/_/g, ' ')}</p><p className="mt-1 text-xs text-muted-foreground">{localDateTime(a.created_at, d.campaign.timezone).replace('T', ' ')} Eastern</p></li>)}</ul>{!d.audit.length && <p className="text-sm text-muted-foreground">No changes yet.</p>}</Panel></div>;
}
