import { useEffect, useState } from 'react';
import { activityRate, campaignWeeks, labels, localDateTime, officeTimestamp, roles, score, tallyClosed } from '@/lib/fill-the-schedule';
import type { ActivityType, Campaign, Ledger } from '@/lib/fill-the-schedule';
import { Panel, Field, TimeField, TeamSelect, input, button, secondary, nameOf, type Writer } from './ui';
export function WeeklyTable({ d, week, writer, select, selected }: { d: Ledger; week: string; writer: Writer; select: (id: string) => void; selected: string }) {
  const rows = d.participants.map(p => ({ p, s: score(d, p, week) })).sort((a, b) => b.s.points - a.s.points || nameOf(d, a.p.employee_id).localeCompare(nameOf(d, b.p.employee_id)));
  const eligible = rows.filter(r => r.s.earned > 0 && r.p.active); const highest = eligible.length ? Math.max(...eligible.map(r => r.s.points)) : null;
  const closed = tallyClosed(week, d.campaign);
  const quarterBest = rows.filter(r => r.p.active).reduce((n, r) => Math.max(n, r.s.quarter), 0);
  const leaders = quarterBest ? rows.filter(r => r.p.active && r.s.quarter === quarterBest).map(r => nameOf(d, r.p.employee_id)) : [];
  return <Panel title="One weekly scorecard for everyone" subtitle={closed ? 'Tally closed. Highest eligible weekly total picks first; tied totals share the same priority.' : 'Live tally. Prize eligibility is provisional until Friday noon Eastern. The final tally closes after December 31.'}>
    <div className="relative min-w-0 overflow-x-auto"><table className="w-full min-w-[840px] text-left text-sm"><caption className="sr-only">Team points and prize eligibility for tally ending {week}</caption><thead className="border-b text-muted-foreground"><tr>{['Team member', 'Approved', 'Pending', 'Verified calls', 'Huddles', 'Quarter', 'Prize status', 'Received'].map(h => <th className="px-3 py-3 font-medium" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(({ p, s }) => <tr key={p.id} className={p.employee_id === selected ? 'bg-primary/5' : ''}><td className="px-3 py-3"><button className="text-left font-medium text-primary underline-offset-4 hover:underline" onClick={() => select(p.employee_id)}>{nameOf(d, p.employee_id)}</button><p className="mt-1 text-xs text-muted-foreground">{p.scoring_role ? roles[p.scoring_role] : 'Scoring group not set'}{!p.active ? ' · Inactive' : ''}</p></td><td className="px-3 py-3 font-semibold">{s.points}</td><td className="px-3 py-3">{s.pending}</td><td className="px-3 py-3">{s.callRecorded ? s.callCount : 'Not recorded'}{p.scoring_role === 'clerical' && <p className="text-xs text-muted-foreground">{d.campaign.clerical_min_calls} required</p>}</td><td className="px-3 py-3">{s.huddleCount}</td><td className="px-3 py-3">{s.quarter}</td><td className="px-3 py-3">{!p.active ? 'Inactive' : !p.scoring_role ? 'Set scoring group' : !s.eligible ? 'Call minimum not met' : `${s.earned} ${closed ? 'earned' : 'provisional'} pick(s)`}{s.earned > 0 && s.points === highest && <p className="text-xs text-primary">First priority{eligible.filter(r => r.s.points === highest).length > 1 ? ' · tied' : ''}</p>}{s.overage > 0 && <p className="mt-1 font-medium text-destructive">Correction: {s.overage} extra pick(s) already received</p>}</td><td className="px-3 py-3"><label><span className="sr-only">Prize picks received by {nameOf(d, p.employee_id)}</span><select className={input} value={s.received} disabled={writer.busy || !closed} onChange={e => void writer.write('fts_set_picks_received', { p_campaign_id: d.campaign.id, p_employee_id: p.employee_id, p_week_key: week, p_count: Number(e.target.value) }, 'Prize picks received updated.')}>
      {[0, 1, 2].map(n => <option key={n} value={n} disabled={n > s.earned && n > s.received}>{n}</option>)}</select></label></td></tr>)}</tbody></table></div>
    <p className="mt-4 text-sm text-muted-foreground">A prize pick means one item from the prize bin. {d.campaign.prize_tier1_points} points earns one; {d.campaign.prize_tier2_points} earns two. Maximum two a week. Record picks only when received.</p>
    <div className="mt-4 rounded-xl border p-4"><p className="text-sm font-medium">${d.campaign.grand_prize_dollars} quarter grand prize</p><p className="mt-1 text-sm text-muted-foreground">{!leaders.length ? 'No quarter points recorded yet.' : `${new Date() < new Date(officeTimestamp(`${d.campaign.ends_on}T23:59`, d.campaign.timezone)) ? 'Current leader' : 'Highest quarter total'}${leaders.length > 1 ? 's (tied)' : ''}: ${leaders.join(', ')} · ${quarterBest} points. ${leaders.length > 1 ? 'A tie needs your decision; no automatic tiebreaker.' : ''}`}</p></div>
  </Panel>;
}
