import { useEffect, useRef, useState, type ReactNode, type FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, Gift, Plus, ShieldCheck, CalendarCheck, ClipboardList } from 'lucide-react';
import { useFillSchedule, useFillScheduleWrite } from '@/hooks/useFillSchedule';
import { activityRate, campaignWeeks, labels, localDateTime, officeTimestamp, reasons, roles, score, tallyClosed, weekKey } from '@/lib/fill-the-schedule';
import type { Activity, ActivityType, Campaign, Ledger, Participant } from '@/lib/fill-the-schedule';

const input = 'min-h-11 w-full rounded-lg border bg-background px-3 py-2 text-sm focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary';
const button = 'inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground disabled:opacity-50';
const secondary = 'inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border bg-background px-3 py-2 text-sm font-medium disabled:opacity-50';
type Writer = ReturnType<typeof useFillScheduleWrite>;
const nameOf = (d: Ledger, id: string) => d.names.find(n => n.id === id)?.display_name || 'Team member';
function Panel({ title, subtitle, children }: { title: string; subtitle?: string; children: ReactNode }) {
  return <section className="rounded-2xl border bg-card p-5 sm:p-6"><h2 className="text-lg font-semibold">{title}</h2>{subtitle && <p className="mt-1 text-sm leading-relaxed text-muted-foreground">{subtitle}</p>}<div className="mt-5">{children}</div></section>;
}
function Field({ title, children }: { title: string; children: ReactNode }) {
  return <label className="block space-y-1.5 text-sm font-medium"><span>{title}</span>{children}</label>;
}
function TimeField({ value, set, campaign }: { value: string; set: (v: string) => void; campaign: Campaign }) {
  let tally = '';
  try { tally = weekKey(officeTimestamp(value, campaign.timezone), campaign); } catch { /* Incomplete date input. */ }
  return <Field title="When the action happened · Eastern time"><input className={input} type="datetime-local" required min={`${campaign.starts_on}T00:00`} max={localDateTime(new Date(), campaign.timezone)} value={value} onChange={e => set(e.target.value)} />{tally && <span className="block text-xs font-normal text-muted-foreground">Counts in the tally ending {tally}.</span>}</Field>;
}
function TeamSelect({ d, value, set }: { d: Ledger; value: string; set: (id: string) => void }) {
  return <Field title="Team member"><select className={input} required value={value} onChange={e => set(e.target.value)}><option value="">Choose a team member</option>{d.participants.filter(p => p.active && d.names.some(n => n.id === p.employee_id && n.employment_status === 'active')).map(p => <option key={p.id} value={p.employee_id}>{nameOf(d, p.employee_id)}</option>)}</select></Field>;
}
function Status({ row }: { row: Activity }) {
  const style = row.status === 'approved' ? 'bg-emerald-500/10 text-emerald-700 dark:text-emerald-300' : row.status === 'pending' ? 'bg-amber-500/10 text-amber-700 dark:text-amber-300' : 'bg-muted text-muted-foreground';
  return <span className={`inline-block rounded-full px-2 py-1 text-xs font-medium ${style}`}>{row.status === 'approved' ? `${row.awarded_points} approved points` : row.status === 'pending' ? 'Awaiting verification' : row.status}</span>;
}

function RecordActions({ d, employeeId, manager, week, writer }: { d: Ledger; employeeId: string; manager: boolean; week: string; writer: Writer }) {
  const [person, setPerson] = useState(employeeId); const [kind, setKind] = useState<ActivityType>('unscheduled_booking');
  const [when, setWhen] = useState(() => localDateTime(new Date(), d.campaign.timezone));
  const [quantity, setQuantity] = useState(1); const [localError, setLocalError] = useState(''); const [confirmed, setConfirmed] = useState(false);
  const qrWhen = useRef<string | null>(null);
  const participant = d.participants.find(p => p.employee_id === person);
  const own = d.participants.find(p => p.employee_id === employeeId);
  const ownScore = own ? score(d, own, week) : null;
  async function submit(e: FormEvent) {
    e.preventDefault(); setLocalError('');
    try {
      const ok = await writer.write(manager && person !== employeeId ? 'fts_record_for' : 'fts_record_own', {
        p_campaign_id: d.campaign.id, ...(manager && person !== employeeId ? { p_employee_id: person } : {}),
        p_type: kind, p_occurred_at: officeTimestamp(when, d.campaign.timezone), p_quantity: kind === 'qr_card' ? quantity : 1,
      }, kind === 'qr_card' ? 'QR card count saved. These points count immediately.' : 'Report saved. It will count after manager verification.', true);
      if (ok) { setConfirmed(false); setWhen(localDateTime(new Date(), d.campaign.timezone)); setQuantity(1); }
    } catch (e) { setLocalError(e instanceof Error ? e.message : 'Choose a valid time.'); }
  }
  return <div className="grid gap-5 lg:grid-cols-[1fr_1.15fr]">
    <Panel title="Team records" subtitle="Record each scheduling action once. No patient names, initials, chart numbers, or appointment details.">
      <div className="space-y-4">
        <div className="rounded-xl bg-primary/5 p-4"><p className="text-sm font-medium">Your QR card running tally</p><p className="mt-2 text-3xl font-bold">{ownScore?.qrCount ?? 0} <span className="text-sm font-normal text-muted-foreground">cards this tally week</span></p><p className="mt-2 text-sm text-muted-foreground">Ask for a review and hand out the QR card. Each completed ask is worth {d.campaign.pts_qr_card} point. Use the form for an earlier action or a batch.</p><p className="mt-2 text-xs text-muted-foreground">Adding now counts in the tally ending {weekKey(new Date(), d.campaign)}.</p><button type="button" className={`${button} mt-4`} disabled={writer.busy || !own?.active || d.campaign.status !== 'active'} onClick={async () => { qrWhen.current ??= new Date().toISOString(); if (await writer.write('fts_record_own', { p_campaign_id: d.campaign.id, p_type: 'qr_card', p_occurred_at: qrWhen.current, p_quantity: 1 }, 'One completed QR ask added to your tally.', true)) qrWhen.current = null; }}><Plus className="h-4 w-4" />Add 1 completed QR ask now</button></div>
        <ol className="list-decimal space-y-2 pl-5 text-sm leading-relaxed"><li>Choose what you did and when it happened.</li><li>QR cards count right away on the honor system.</li><li>Scheduling and chairside card reports wait for manager verification. Pending reports earn no points yet.</li><li>Find an error? Withdraw your pending report or QR entry below, then record the correct action.</li></ol>
        <p className="rounded-lg border p-3 text-sm">You do not tally huddles, calls, posted Google reviews, or bonuses here. Your manager handles those.</p>
      </div>
    </Panel>
    <Panel title={manager ? 'Record an action for yourself or a teammate' : 'Record your action'}>
      <form onSubmit={submit} className="space-y-4">
        {manager && <TeamSelect d={d} value={person} set={setPerson} />}
        <Field title="What you did"><select className={input} value={kind} onChange={e => { setKind(e.target.value as ActivityType); setConfirmed(false); }}>{(['qr_card', 'unscheduled_booking', 'operative_handoff', 'chairside_card'] as ActivityType[]).map(k => <option key={k} value={k}>{labels[k]}</option>)}</select></Field>
        <p className="text-sm text-muted-foreground">{activityRate(kind, d.campaign, participant?.scoring_role ?? null) == null ? 'Points not set. This can be reported, but approval is blocked until the manager sets the rate.' : `${activityRate(kind, d.campaign, participant?.scoring_role ?? null)} point(s) each${kind === 'qr_card' ? ' · counts immediately' : ' · after verification'}`}</p>
        <TimeField value={when} set={setWhen} campaign={d.campaign} />
        {kind === 'qr_card' && <Field title="Number of completed asks + cards handed out"><input className={input} type="number" min="1" max="20" step="1" value={quantity} required onChange={e => setQuantity(Number(e.target.value))} /></Field>}
        <label className="flex gap-3 text-sm leading-relaxed"><input type="checkbox" className="mt-1 h-4 w-4 shrink-0" required checked={confirmed} onChange={e => setConfirmed(e.target.checked)} /><span>{kind === 'qr_card' ? 'The review was requested and the QR card was handed out.' : kind === 'chairside_card' ? 'The case was over $10,000 and card on file was presented chairside.' : 'This action was completed and has not already been reported.'}</span></label>
        {localError && <p role="alert" className="text-sm text-destructive">{localError}</p>}
        <button className={button} disabled={writer.busy || !participant?.active || d.campaign.status !== 'active'}><Plus className="h-4 w-4" />{kind === 'qr_card' ? 'Add to QR tally' : 'Submit for verification'}</button>
      </form>
    </Panel>
  </div>;
}

function ActivityHistory({ d, employeeId, manager, writer, week }: { d: Ledger; employeeId: string; manager: boolean; writer: Writer; week: string }) {
  const [allWeeks, setAllWeeks] = useState(false); const [page, setPage] = useState(0);
  const [reason, setReason] = useState<keyof typeof reasons>('recorded_in_error');
  const visible = d.activities.filter(a => (manager || a.employee_id === employeeId) && (allWeeks || a.tally_week === week)).sort((a, b) => b.occurred_at.localeCompare(a.occurred_at) || b.id.localeCompare(a.id));
  useEffect(() => setPage(0), [week, allWeeks]);
  return <Panel title={manager ? 'Activity ledger and corrections' : 'Your reports and awarded points'} subtitle="Every correction keeps a history. Approved scheduling entries can only be reversed by a manager.">
    <div className="mb-4 flex flex-wrap items-end gap-4"><label className="flex min-h-10 items-center gap-2 text-sm"><input type="checkbox" checked={allWeeks} onChange={e => setAllWeeks(e.target.checked)} />Show the whole quarter</label><div className="max-w-sm"><Field title="Reason for a correction"><select className={input} value={reason} onChange={e => setReason(e.target.value as keyof typeof reasons)}>{Object.entries(reasons).filter(([key]) => manager || ['recorded_in_error', 'duplicate_entry'].includes(key)).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></Field></div></div>
    {!visible.length ? <p className="text-sm text-muted-foreground">No entries for this view yet.</p> : <ul className="divide-y">{visible.slice(page * 10, page * 10 + 10).map(a => {
      const canWithdraw = a.employee_id === employeeId && (a.status === 'pending' || (a.status === 'approved' && a.activity_type === 'qr_card'));
      const hasBonus = d.activities.some(b => b.parent_id === a.id && b.status === 'approved');
      return <li key={a.id} className="flex flex-wrap justify-between gap-3 py-4"><div className="min-w-0 flex-1"><p className="text-sm font-medium">{labels[a.activity_type]}{a.quantity > 1 ? ` × ${a.quantity}` : ''}</p><p className="mt-1 text-xs text-muted-foreground">{manager && `${nameOf(d, a.employee_id)} · `}Entry {a.entry_code} · {localDateTime(a.occurred_at, d.campaign.timezone).replace('T', ' ')} Eastern · Tally {a.tally_week}{a.parent_id && ` · Linked to ${d.activities.find(b => b.id === a.parent_id)?.entry_code ?? 'origin'}`}</p><div className="mt-2"><Status row={a} />{a.reason_code && <span className="ml-2 text-xs text-muted-foreground">{reasons[a.reason_code as keyof typeof reasons]}</span>}</div></div>
        <div className="flex items-center gap-2">{manager && a.status === 'approved' ? <button className={secondary} disabled={writer.busy || hasBonus} title={hasBonus ? 'Reverse the linked bonuses first.' : undefined} onClick={() => void writer.write('fts_reverse', { p_activity_id: a.id, p_reason: reason }, 'Entry reversed. Points and eligibility recalculated.')}>{hasBonus ? 'Reverse bonuses first' : 'Reverse entry'}</button> : canWithdraw && <button className={secondary} disabled={writer.busy} onClick={() => void writer.write('fts_withdraw_own', { p_activity_id: a.id, p_reason: reason }, 'Entry withdrawn. Record a new entry if needed.')}>Withdraw entry</button>}</div>
      </li>;
    })}</ul>}
    {visible.length > 10 && <div className="mt-4 flex items-center justify-between gap-3"><button className={secondary} disabled={!page} onClick={() => setPage(p => p - 1)}>Previous</button><span className="text-sm">Page {page + 1} of {Math.ceil(visible.length / 10)}</span><button className={secondary} disabled={(page + 1) * 10 >= visible.length} onClick={() => setPage(p => p + 1)}>Next</button></div>}
  </Panel>;
}

function VerificationQueue({ d, writer }: { d: Ledger; writer: Writer }) {
  const [reason, setReason] = useState('not_verified_in_record');
  const pending = d.activities.filter(a => a.status === 'pending').sort((a, b) => a.occurred_at.localeCompare(b.occurred_at));
  return <Panel title={`Scheduling reports to verify · ${pending.length}`} subtitle="Check the original action in Dentrix or MaxAssist. Approve only after checking; these reports are not points yet. The entry code identifies the report here, without a patient identifier.">
    <div className="mb-4 max-w-sm"><Field title="Reason if rejecting"><select className={input} value={reason} onChange={e => setReason(e.target.value)}>{Object.entries(reasons).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></Field></div>
    {!pending.length ? <div className="flex items-center gap-2 text-sm text-muted-foreground"><CheckCircle2 className="h-5 w-5" />All caught up. No reports awaiting verification.</div> : <ul className="divide-y">{pending.map(a => {
      const rate = activityRate(a.activity_type, d.campaign, d.participants.find(p => p.employee_id === a.employee_id)?.scoring_role ?? null);
      return <li key={a.id} className="flex flex-wrap items-center justify-between gap-3 py-4"><div className="flex-1"><p className="font-medium">{nameOf(d, a.employee_id)}</p><p className="mt-1 text-sm">{labels[a.activity_type]}</p><p className="mt-1 text-xs text-muted-foreground">Entry {a.entry_code} · {localDateTime(a.occurred_at, d.campaign.timezone).replace('T', ' ')} Eastern · Tally {a.tally_week} · {rate == null ? 'Points not set' : `${rate * a.quantity} points if approved`}</p></div><div className="flex gap-2"><button className={secondary} disabled={writer.busy} onClick={() => void writer.write('fts_verify', { p_activity_id: a.id, p_approve: false, p_reason: reason }, 'Report rejected. No points awarded.')}>Reject</button><button className={button} disabled={writer.busy || rate == null} onClick={() => void writer.write('fts_verify', { p_activity_id: a.id, p_approve: true }, 'Report verified. Points now count.')}>Verify + approve</button></div></li>;
    })}</ul>}
  </Panel>;
}

function WeeklyTable({ d, week, writer, select, selected }: { d: Ledger; week: string; writer: Writer; select: (id: string) => void; selected: string }) {
  const rows = d.participants.map(p => ({ p, s: score(d, p, week) })).sort((a, b) => b.s.points - a.s.points || nameOf(d, a.p.employee_id).localeCompare(nameOf(d, b.p.employee_id)));
  const eligible = rows.filter(r => r.s.earned > 0 && r.p.active); const highest = eligible.length ? Math.max(...eligible.map(r => r.s.points)) : null;
  const closed = tallyClosed(week, d.campaign);
  const quarterBest = rows.filter(r => r.p.active).reduce((n, r) => Math.max(n, r.s.quarter), 0);
  const leaders = quarterBest ? rows.filter(r => r.p.active && r.s.quarter === quarterBest).map(r => nameOf(d, r.p.employee_id)) : [];
  return <Panel title="One weekly scorecard for everyone" subtitle={closed ? 'Tally closed. Highest eligible weekly total picks first; tied totals share the same priority.' : 'Live tally. Prize eligibility is provisional until Friday noon Eastern. The final tally closes after December 31.'}>
    <div className="relative min-w-0 overflow-x-auto"><table className="w-full min-w-[840px] text-left text-sm"><caption className="sr-only">Team points and prize eligibility for tally ending {week}</caption><thead className="border-b text-muted-foreground"><tr>{['Team member', 'Approved', 'Pending', 'Verified calls', 'Huddles', 'Quarter', 'Prize status', 'Received'].map(h => <th className="px-3 py-3 font-medium" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y">{rows.map(({ p, s }) => <tr key={p.id} className={p.employee_id === selected ? 'bg-primary/5' : ''}><td className="px-3 py-3"><button className="text-left font-medium text-primary underline-offset-4 hover:underline" onClick={() => select(p.employee_id)}>{nameOf(d, p.employee_id)}</button><p className="mt-1 text-xs text-muted-foreground">{p.scoring_role ? roles[p.scoring_role] : 'Scoring group not set'}{!p.active ? ' · Inactive' : ''}</p></td><td className="px-3 py-3 font-semibold">{s.points}</td><td className="px-3 py-3">{s.pending}</td><td className="px-3 py-3">{s.callRecorded ? s.callCount : 'Not recorded'}{p.scoring_role === 'clerical' && <p className="text-xs text-muted-foreground">{d.campaign.clerical_min_calls} required</p>}</td><td className="px-3 py-3">{s.huddleCount}</td><td className="px-3 py-3">{s.quarter}</td><td className="px-3 py-3">{!p.active ? 'Inactive' : !p.scoring_role ? 'Set scoring group' : !s.eligible ? 'Call minimum not met' : `${s.earned} ${closed ? 'earned' : 'provisional'} pick(s)`}{s.earned > 0 && s.points === highest && <p className="text-xs text-primary">First priority{eligible.filter(r => r.s.points === highest).length > 1 ? ' · tied' : ''}</p>}{s.overage > 0 && <p className="mt-1 font-medium text-destructive">Correction: {s.overage} extra pick(s) already received</p>}</td><td className="px-3 py-3"><label><span className="sr-only">Prize picks received by {nameOf(d, p.employee_id)}</span><select className={input} value={s.received} disabled={writer.busy || !closed} onChange={e => void writer.write('fts_set_picks_received', { p_campaign_id: d.campaign.id, p_employee_id: p.employee_id, p_week_key: week, p_count: Number(e.target.value) }, 'Prize picks received updated.')}>
      {[0, 1, 2].map(n => <option key={n} value={n} disabled={n > s.earned && n > s.received}>{n}</option>)}</select></label></td></tr>)}</tbody></table></div>
    <p className="mt-4 text-sm text-muted-foreground">A prize pick means one item from the prize bin. {d.campaign.prize_tier1_points} points earns one; {d.campaign.prize_tier2_points} earns two. Maximum two a week. Record picks only when received.</p>
    <div className="mt-4 rounded-xl border p-4"><p className="text-sm font-medium">${d.campaign.grand_prize_dollars} quarter grand prize</p><p className="mt-1 text-sm text-muted-foreground">{!leaders.length ? 'No quarter points recorded yet.' : `${new Date() < new Date(officeTimestamp(`${d.campaign.ends_on}T23:59`, d.campaign.timezone)) ? 'Current leader' : 'Highest quarter total'}${leaders.length > 1 ? 's (tied)' : ''}: ${leaders.join(', ')} · ${quarterBest} points. ${leaders.length > 1 ? 'A tie needs your decision; no automatic tiebreaker.' : ''}`}</p></div>
  </Panel>;
}

function VerifiedCalls({ d, week, selected, writer }: { d: Ledger; week: string; selected: string; writer: Writer }) {
  const existing = d.calls.find(c => c.employee_id === selected && c.week_key === week);
  const [count, setCount] = useState(existing?.verified_count?.toString() ?? '');
  useEffect(() => setCount(existing?.verified_count?.toString() ?? ''), [week, selected, existing?.verified_count]);
  return <Panel title="Documented unscheduled treatment calls" subtitle="Check same-day MaxAssist notes and phone codes. No note, no call point. Save the total for this tally week; an edit replaces the total.">
    <form className="space-y-4" onSubmit={e => { e.preventDefault(); void writer.write('fts_set_weekly_calls', { p_campaign_id: d.campaign.id, p_employee_id: selected, p_week_key: week, p_count: Number(count) }, 'Verified weekly call total saved.'); }}><p className="text-sm font-medium">{nameOf(d, selected)} · Tally {week}</p><Field title="Verified call total"><input className={input} type="number" min="0" max="500" step="1" value={count} onChange={e => setCount(e.target.value)} required /></Field><p className="text-sm text-muted-foreground">{d.campaign.pts_call} point per call. Clerical staff need {d.campaign.clerical_min_calls} verified calls to enter that week’s prize drawing.</p><button className={button} disabled={!selected || writer.busy}>Save verified call total</button></form>
  </Panel>;
}

function Huddles({ d, writer }: { d: Ledger; writer: Writer }) {
  const today = localDateTime(new Date(), d.campaign.timezone).slice(0, 10);
  const [date, setDate] = useState(today); const [checked, setChecked] = useState<string[]>([]); const [dirty, setDirty] = useState(false);
  const existing = d.huddles.filter(h => h.huddle_date === date && h.on_time).map(h => h.employee_id).sort().join(',');
  useEffect(() => { if (!dirty) setChecked(existing ? existing.split(',') : []); }, [date, existing, dirty]);
  return <Panel title="On time for huddle" subtitle="You mark attendance here. Team members do not track it, and time-clock punches are not used to infer it.">
    <form className="space-y-4" onSubmit={async e => { e.preventDefault(); if (await writer.write('fts_save_huddle', { p_campaign_id: d.campaign.id, p_date: date, p_on_time: checked }, 'Huddle attendance saved. Re-saving this date corrects it without adding duplicate points.')) setDirty(false); }}>
      <Field title="Huddle date · Eastern time"><input className={input} type="date" required min={d.campaign.starts_on} max={today < d.campaign.ends_on ? today : d.campaign.ends_on} value={date} onChange={e => { setDate(e.target.value); setDirty(false); }} /></Field>
      <p className="text-sm text-muted-foreground">Check everyone who was on time. Each earns {d.campaign.pts_huddle} point for this date. Unchecked people receive no point.</p>
      <div className="grid gap-2 sm:grid-cols-2">{d.participants.filter(p => p.active && d.names.some(n => n.id === p.employee_id && n.employment_status === 'active')).map(p => <label key={p.id} className="flex min-h-11 items-center gap-3 rounded-lg border p-3 text-sm"><input type="checkbox" className="h-4 w-4" checked={checked.includes(p.employee_id)} onChange={e => { setDirty(true); setChecked(ids => e.target.checked ? [...ids, p.employee_id] : ids.filter(id => id !== p.employee_id)); }} />{nameOf(d, p.employee_id)}</label>)}</div>
      <button className={button} disabled={writer.busy}>Save huddle attendance</button>
    </form>
  </Panel>;
}

function ReviewAndBonus({ d, selected, writer }: { d: Ledger; selected: string; writer: Writer }) {
  const [kind, setKind] = useState<'google_review' | 'attend_bonus' | 'prepay_bonus'>('google_review');
  const [when, setWhen] = useState(() => localDateTime(new Date(), d.campaign.timezone)); const [parent, setParent] = useState(''); const [verified, setVerified] = useState(false); const [error, setError] = useState('');
  const participant = d.participants.find(p => p.employee_id === selected);
  const origins = d.activities.filter(a => a.employee_id === selected && a.status === 'approved' && (kind === 'attend_bonus' ? a.activity_type === 'unscheduled_booking' : ['unscheduled_booking', 'operative_handoff'].includes(a.activity_type)) && !d.activities.some(b => b.parent_id === a.id && b.activity_type === kind && b.status === 'approved')).sort((a, b) => b.occurred_at.localeCompare(a.occurred_at));
  useEffect(() => { setParent(''); setVerified(false); }, [kind, selected]);
  const rate = activityRate(kind, d.campaign, participant?.scoring_role ?? null);
  return <Panel title="Posted Google reviews and linked bonuses" subtitle="Verify in the original system. Record no reviewer names, review text, patient details, or financial account details here.">
    <form className="space-y-4" onSubmit={async e => { e.preventDefault(); setError(''); try {
      const params = kind === 'google_review' ? { p_campaign_id: d.campaign.id, p_employee_id: selected, p_occurred_at: officeTimestamp(when, d.campaign.timezone) } : { p_parent_id: parent, p_type: kind, p_occurred_at: officeTimestamp(when, d.campaign.timezone) };
      if (await writer.write(kind === 'google_review' ? 'fts_award_review' : 'fts_award_bonus', params, 'Verified points awarded.', true)) { setVerified(false); setParent(''); setWhen(localDateTime(new Date(), d.campaign.timezone)); }
    } catch (e) { setError(e instanceof Error ? e.message : 'Choose a valid time.'); } }}>
      <p className="font-medium">{nameOf(d, selected)}</p><Field title="Verified action"><select className={input} value={kind} onChange={e => setKind(e.target.value as typeof kind)}><option value="google_review">Posted Google review names this team member</option><option value="attend_bonus">Booked appointment attended · linked bonus</option><option value="prepay_bonus">Prepayment confirmed · linked bonus</option></select></Field>
      <p className="text-sm text-muted-foreground">{rate == null ? 'Set this team member’s scoring group in Settings before awarding a review.' : `${rate} points. ${kind === 'google_review' ? `Scoring group: ${participant?.scoring_role ? roles[participant.scoring_role] : 'not set'}.` : 'One bonus of this kind per originating action.'}`}</p>
      {kind !== 'google_review' && <><Field title="Original approved action"><select className={input} value={parent} required onChange={e => setParent(e.target.value)}><option value="">Choose the originating entry</option>{origins.map(a => <option key={a.id} value={a.id}>{a.entry_code} · {labels[a.activity_type]} · {localDateTime(a.occurred_at, d.campaign.timezone).replace('T', ' ')}</option>)}</select></Field><p className="text-xs text-muted-foreground">{origins.length ? 'Match the entry to the action you verified outside Purple Envelope.' : 'No eligible original action. Approve the booking or handoff first, or check whether its bonus was already awarded.'}</p></>}
      <TimeField value={when} set={setWhen} campaign={d.campaign} />
      <label className="flex gap-3 text-sm"><input type="checkbox" className="mt-1 h-4 w-4 shrink-0" required checked={verified} onChange={e => setVerified(e.target.checked)} /><span>{kind === 'google_review' ? 'I verified a posted Google review names this team member and it has not already been counted.' : kind === 'prepay_bonus' ? 'I verified actual prepayment for this original action. Card on file alone is not prepayment.' : 'I verified attendance for this original unscheduled-list booking.'}</span></label>
      {error && <p role="alert" className="text-sm text-destructive">{error}</p>}<button className={button} disabled={writer.busy || !selected || rate == null}>Award verified points</button>
    </form>
  </Panel>;
}

function OpenHours({ d, week, writer }: { d: Ledger; week: string; writer: Writer }) {
  const saved = d.metrics.find(m => m.week_key === week)?.doctor_open_hours;
  const [hours, setHours] = useState(saved == null ? '' : String(saved));
  useEffect(() => setHours(saved == null ? '' : String(saved)), [week, saved]);
  return <Panel title="Office goal: fill doctor open time" subtitle={`Record actual open hours for this tally week. Goal: under ${d.campaign.open_hours_goal} hours. A blank value means not recorded, never zero.`}>
    <form className="flex flex-wrap items-end gap-3" onSubmit={e => { e.preventDefault(); void writer.write('fts_set_open_hours', { p_campaign_id: d.campaign.id, p_week_key: week, p_hours: hours === '' ? null : Number(hours) }, 'Office open hours saved.'); }}><div className="flex-1"><Field title="Doctor open hours"><input className={input} type="number" min="0" max="200" step="0.01" value={hours} placeholder="Not recorded" onChange={e => setHours(e.target.value)} /></Field></div><button className={button} disabled={writer.busy}>Save open hours</button></form>
  </Panel>;
}

function Rules({ c }: { c: Campaign }) {
  return <div className="space-y-5"><Panel title="What earns points" subtitle="Team records the actions on the left. The manager handles verification and the items in the second table.">
    <h3 className="mb-3 font-medium">Team records</h3><div className="relative min-w-0 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b"><tr><th className="py-3 pr-4">Completed action</th><th className="py-3 pr-4">Points</th><th className="py-3">How it counts</th></tr></thead><tbody className="divide-y">{(['qr_card', 'unscheduled_booking', 'operative_handoff', 'chairside_card'] as ActivityType[]).map(k => <tr key={k}><td className="py-3 pr-4">{labels[k]}</td><td className="py-3 pr-4">{activityRate(k, c, null) ?? 'Not set'}</td><td className="py-3">{k === 'qr_card' ? 'Honor system; counts right away' : k === 'chairside_card' && c.pts_chairside_card == null ? 'Report now; approval blocked until rate is set' : 'Manager verifies first'}</td></tr>)}</tbody></table></div>
    <h3 className="mb-3 mt-6 font-medium">Manager verifies and records</h3><div className="relative min-w-0 overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b"><tr><th className="py-3 pr-4">Action</th><th className="py-3 pr-4">Points</th><th className="py-3">Requirement</th></tr></thead><tbody className="divide-y"><tr><td className="py-3 pr-4">Documented unscheduled treatment calls</td><td className="py-3 pr-4">{c.pts_call} each</td><td className="py-3">Same-day MaxAssist note and phone code; manager saves the verified weekly total</td></tr><tr><td className="py-3 pr-4">Posted Google review that names you</td><td className="py-3 pr-4">Doctor {c.pts_review_doctor}<br />Hygienist {c.pts_review_hygienist}<br />Clerical {c.pts_review_clerical}<br />Assistant {c.pts_review_assistant}</td><td className="py-3">Actual posted review; manager verifies; confirmed scoring group required</td></tr><tr><td className="py-3 pr-4">Booked appointment attended</td><td className="py-3 pr-4">+{c.pts_attend_bonus}</td><td className="py-3">Linked to an approved unscheduled-list booking; once per original action</td></tr><tr><td className="py-3 pr-4">Prepayment confirmed</td><td className="py-3 pr-4">+{c.pts_prepay_bonus}</td><td className="py-3">Linked to an approved booking or operative handoff; once per original action; card on file is not prepayment</td></tr><tr><td className="py-3 pr-4">On time for huddle</td><td className="py-3 pr-4">{c.pts_huddle} per date</td><td className="py-3">Manager checks attendance; no team tally needed</td></tr></tbody></table></div>
  </Panel><Panel title="Prize picks, weekly tally, and office goal"><ul className="list-disc space-y-3 pl-5 text-sm leading-relaxed"><li>A prize pick is one item from the prize bin. {c.prize_tier1_points} approved points earns one pick; {c.prize_tier2_points} earns two. Maximum two per week. Pending reports do not count.</li><li>Clerical team members need at least {c.clerical_min_calls} verified calls each week to qualify. A scoring group must be set for every prize recipient.</li><li>Points are tallied Friday at noon Eastern time. Actions at or after noon Friday roll into the next tally week. The final partial tally includes actions through December 31. Bonuses count in the week the bonus action happened.</li><li>The highest eligible weekly total picks first. Tied totals share priority. Picks happen Friday or the following Monday afternoon; the manager marks items as received.</li><li>The prize bin includes small prizes and gift cards, with a few bigger surprises. The highest quarter total wins ${c.grand_prize_dollars}; tied quarter leaders are shown for the manager to resolve.</li><li>Office goal: doctor open time under {c.open_hours_goal} hours per week. Actual hours are entered by the manager; missing data is shown as “Not recorded.”</li><li>Approved points are preserved at the rate in effect when awarded. Corrections are logged. If a correction reduces eligibility after prizes were received, the manager sees the discrepancy.</li></ul></Panel></div>;
}

function Settings({ d, writer }: { d: Ledger; writer: Writer }) {
  const [cardPoints, setCardPoints] = useState(d.campaign.pts_chairside_card == null ? '' : String(d.campaign.pts_chairside_card));
  return <div className="space-y-5"><Panel title="Confirm scoring groups" subtitle="These groups control Google review points and the clerical call minimum. They do not change Purple Envelope permissions or employee job assignments. Existing roster members are included; no invitations are sent.">
    <div className="divide-y">{d.participants.map(p => <div className="flex flex-wrap items-center gap-3 py-3" key={p.id}><div className="min-w-40 flex-1"><p className="text-sm font-medium">{nameOf(d, p.employee_id)}</p>{!p.scoring_role && <p className="text-xs text-amber-700 dark:text-amber-300">Confirmation needed for review points and prizes</p>}</div><label className="w-44"><span className="sr-only">Scoring group for {nameOf(d, p.employee_id)}</span><select className={input} disabled={writer.busy} value={p.scoring_role ?? ''} onChange={e => void writer.write('fts_set_scoring_role', { p_campaign_id: d.campaign.id, p_employee_id: p.employee_id, p_role: e.target.value || null, p_active: p.active }, 'Scoring group updated. Previously awarded review points stay unchanged.')}><option value="">Not confirmed</option>{Object.entries(roles).map(([k, v]) => <option key={k} value={k}>{v}</option>)}</select></label><label className="flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={p.active} disabled={writer.busy} onChange={e => void writer.write('fts_set_scoring_role', { p_campaign_id: d.campaign.id, p_employee_id: p.employee_id, p_role: p.scoring_role, p_active: e.target.checked }, 'Campaign participation updated.')} />Participating</label></div>)}</div>
  </Panel><Panel title="Chairside card point rate" subtitle="The case threshold is over $10,000. The point value was not confirmed, so it stays unset until you set it here. This does not award the prepayment bonus."><form className="max-w-md space-y-4" onSubmit={e => { e.preventDefault(); void writer.write('fts_set_rate', { p_campaign_id: d.campaign.id, p_key: 'pts_chairside_card', p_value: cardPoints === '' ? null : Number(cardPoints) }, 'Chairside card point rate saved. Approved points stay unchanged.'); }}><Field title="Points per verified chairside card presentation"><input className={input} type="number" min="0" max="100" step="1" placeholder="Not set" value={cardPoints} onChange={e => setCardPoints(e.target.value)} /></Field><button className={button} disabled={writer.busy}>Save point rate</button><p className="text-xs text-muted-foreground">Leave blank to keep approvals blocked. Already-awarded points are never rewritten.</p></form></Panel>
    <Panel title="Recent change history" subtitle="Manager-only history of reports, verification, corrections, and settings."><ul className="divide-y text-sm">{d.audit.slice().sort((a, b) => b.created_at.localeCompare(a.created_at)).slice(0, 25).map(a => <li className="py-3" key={a.id}><p>{a.employee_id ? nameOf(d, a.employee_id) : 'Campaign'} · {a.entity.replace(/_/g, ' ')} · {a.action.replace(/_/g, ' ')}</p><p className="mt-1 text-xs text-muted-foreground">{localDateTime(a.created_at, d.campaign.timezone).replace('T', ' ')} Eastern</p></li>)}</ul>{!d.audit.length && <p className="text-sm text-muted-foreground">No changes yet.</p>}</Panel></div>;
}

export default function FillSchedule() {
  const { data: d, ctx, manager, isLoading, error, contextLoading, contextError, refetch } = useFillSchedule();
  const writer = useFillScheduleWrite();
  const [tab, setTab] = useState<'team' | 'manager' | 'rules' | 'settings'>('team');
  const [chosenWeek, setChosenWeek] = useState(''); const [selected, setSelected] = useState('');
  if (isLoading || contextLoading) return <div className="p-8" role="status">Loading Fill the Schedule…</div>;
  if (error || contextError) return <div className="mx-auto max-w-3xl p-8"><h1 className="text-2xl font-bold">Fill the Schedule</h1><p className="my-4" role="alert">The campaign could not be loaded. Your scores have not been changed.</p><button className={button} onClick={() => void refetch()}>Try again</button></div>;
  if (!d || !ctx) return <div className="mx-auto max-w-3xl p-8"><Link to="/workplace" className="text-primary">Back to Workplace</Link><h1 className="mt-5 text-2xl font-bold">Fill the Schedule</h1><p className="mt-3 text-muted-foreground">No Fill the Schedule campaign is configured for your office.</p></div>;
  const c = d.campaign; const weeks = campaignWeeks(c); const currentWeek = weekKey(new Date(), c); const week = chosenWeek || currentWeek;
  const person = selected || ctx.employee_id || d.participants[0]?.employee_id || '';
  const own = d.participants.find(p => p.employee_id === ctx.employee_id); const ownScore = own ? score(d, own, week) : null;
  const hours = d.metrics.find(m => m.week_key === week)?.doctor_open_hours;
  const closed = tallyClosed(week, c); const missingRoles = d.participants.filter(p => p.active && !p.scoring_role).length;
  return <div className="mx-auto max-w-7xl space-y-6 p-4 pb-16 sm:p-6 lg:p-8">
    <Link to="/workplace" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4" />Workplace</Link>
    <header className="flex flex-wrap items-end justify-between gap-5"><div><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-primary">Q4 push · October 1 to December 31, 2026</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Fill the Schedule</h1><p className="mt-2 text-muted-foreground">Clear actions. Verified points. More patients in the chair.</p></div><div className="w-full sm:w-60"><Field title="Tally ending"><select className={input} value={week} onChange={e => setChosenWeek(e.target.value)}>{weeks.map(w => <option key={w} value={w}>{w}{w === c.ends_on ? ' · final tally' : ' · Friday noon'}</option>)}</select></Field></div></header>
    <div className="grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border bg-card p-5"><p className="text-sm text-muted-foreground">Your approved weekly points</p><p className="mt-2 text-3xl font-bold">{ownScore?.points ?? 0}</p><p className="mt-2 text-xs text-muted-foreground">{ownScore?.pending ?? 0} reports pending · {ownScore?.quarter ?? 0} quarter points</p></div><div className="rounded-2xl border bg-card p-5"><p className="flex items-center gap-2 text-sm text-muted-foreground"><Gift className="h-4 w-4" />Your prize picks {closed ? '' : '· provisional'}</p><p className="mt-2 text-3xl font-bold">{ownScore?.earned ?? 0} <span className="text-base font-normal text-muted-foreground">earned</span></p><p className="mt-2 text-xs text-muted-foreground">{!own?.scoring_role ? 'Scoring group needs manager confirmation' : own.scoring_role === 'clerical' && !ownScore?.eligible ? `${ownScore?.callCount ?? 0}/${c.clerical_min_calls} verified calls; call minimum required` : `${ownScore?.received ?? 0} received · ${ownScore?.remaining ?? 0} remaining`}</p></div><div className="rounded-2xl border bg-primary/5 p-5"><p className="text-sm text-muted-foreground">Office doctor open time</p><p className="mt-2 text-3xl font-bold">{hours == null ? <span className="text-xl">Not recorded</span> : <>{hours} <span className="text-base font-normal">hours</span></>}</p><p className="mt-2 text-xs text-muted-foreground">Goal: under {c.open_hours_goal} hours/week{hours != null && hours < c.open_hours_goal ? ' · Goal met' : ''}</p></div></div>
    {c.status !== 'active' && <p className="rounded-lg border p-4 text-sm">This campaign is closed. History is available; new entries cannot be saved.</p>}
    {manager && missingRoles > 0 && <div className="rounded-xl border border-amber-500/30 bg-amber-500/5 p-4 text-sm">{missingRoles} team member(s) need scoring group confirmation. <button className="font-medium text-primary underline" onClick={() => setTab('settings')}>Open Settings</button> to enable their review points and prize eligibility.</div>}
    <div className="sticky top-0 z-10 rounded-xl border bg-background/95 p-3 shadow-sm"><div className="flex flex-wrap gap-2" role="tablist" aria-label="Campaign work areas">{([{ key: 'team', label: 'Team records', icon: ClipboardList }, ...(manager ? [{ key: 'manager', label: 'Manager verifies', icon: ShieldCheck }] : []), { key: 'rules', label: 'Point rules', icon: Gift }, ...(manager ? [{ key: 'settings', label: 'Settings', icon: CalendarCheck }] : [])] as const).map(t => <button key={t.key} role="tab" aria-selected={tab === t.key} aria-controls="campaign-panel" className={tab === t.key ? button : secondary} onClick={() => setTab(t.key as typeof tab)}><t.icon className="h-4 w-4" />{t.label}</button>)}</div>{writer.error && <p className="mt-3 text-sm text-destructive" role="alert">{writer.error}</p>}{writer.message && <p className="mt-3 text-sm text-emerald-700 dark:text-emerald-300" role="status">{writer.message}</p>}{writer.busy && <p className="mt-3 text-sm text-muted-foreground" role="status">Saving…</p>}</div>
    <div id="campaign-panel" role="tabpanel" className="space-y-5">
      {tab === 'team' && <><RecordActions d={d} employeeId={ctx.employee_id} manager={manager} week={week} writer={writer} /><ActivityHistory d={d} employeeId={ctx.employee_id} manager={false} week={week} writer={writer} /></>}
      {tab === 'manager' && manager && <><WeeklyTable d={d} week={week} writer={writer} select={setSelected} selected={person} /><OpenHours d={d} week={week} writer={writer} /><VerificationQueue d={d} writer={writer} /><div className="rounded-2xl border bg-card p-5"><TeamSelect d={d} value={person} set={setSelected} /><p className="mt-2 text-sm text-muted-foreground">Choose a team member for the call and review/bonus forms below, or select their name in the weekly scorecard.</p></div><div className="grid gap-5 lg:grid-cols-2"><VerifiedCalls key={`${person}-${week}`} d={d} week={week} selected={person} writer={writer} /><ReviewAndBonus d={d} selected={person} writer={writer} /></div><Huddles d={d} writer={writer} /><ActivityHistory d={d} employeeId={ctx.employee_id} manager week={week} writer={writer} /></>}
      {tab === 'rules' && <Rules c={c} />}{tab === 'settings' && manager && <Settings d={d} writer={writer} />}
    </div><p className="text-xs leading-relaxed text-muted-foreground">No patient information belongs in this campaign. Use Dentrix, MaxAssist, and Google for verification. Staff see their own records and the shared office goal; managers see the complete scorecard.</p>
  </div>;
}
