import { useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useOrgContext } from '@/hooks/useOrgContext';
import { useAuth } from '@/hooks/useAuth';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { AlertCircle, CheckCircle2, FileUp, Download } from 'lucide-react';
import { toast } from 'sonner';
import { validatePreparedReport, type PreparedReport, type ReportRow } from '@/lib/prepared-report';

const money = (v: unknown) => typeof v === 'number' ? new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v/100) : 'Not recorded';
const hours = (m: number) => `${Math.floor(m/60)}:${String(m%60).padStart(2,'0')}`;
type Column = { key: string; label: string; format?: (value: any, row: ReportRow) => React.ReactNode };
function Table({ rows, columns }: {rows: ReportRow[]; columns: Column[]}) {
  const [search,setSearch] = useState('');
  const visible = rows.filter(row=>columns.some(c=>String(row[c.key]??'').toLowerCase().includes(search.toLowerCase())));
  return <div className="space-y-3"><Input aria-label="Filter report rows" placeholder="Filter rows by date, name or code" value={search} onChange={e=>setSearch(e.target.value)} className="max-w-md"/><p className="text-xs text-muted-foreground">{visible.length} of {rows.length} rows</p><div className="overflow-auto max-h-[65vh] rounded-lg border"><table className="w-full text-sm"><thead className="sticky top-0 bg-muted"><tr>{columns.map(c=><th className="p-3 text-left whitespace-nowrap" key={c.key}>{c.label}</th>)}</tr></thead><tbody>{visible.map((row,i)=><tr key={i} className="border-t hover:bg-muted/40">{columns.map(c=><td className="p-3 align-top tabular-nums" key={c.key}>{c.format ? c.format(row[c.key],row) : String(row[c.key]??'Not recorded')}</td>)}</tr>)}</tbody></table>{!visible.length&&<p className="p-6 text-muted-foreground">No matching rows.</p>}</div></div>;
}
const financial: Column[] = [{key:'posted_charges_cents',label:'Posted charges',format:money},{key:'recorded_payments_cents',label:'Receipts',format:money},{key:'credit_adjustments_cents',label:'Credit adjustments',format:money},{key:'charge_adjustments_cents',label:'Charge adjustments',format:money},{key:'posted_refunds_cents',label:'Refunds included in charge adjustments',format:money}];
export default function ReportHistory() {
  const {data:ctx} = useOrgContext(); const {user} = useAuth(); const qc = useQueryClient();
  const file = useRef<HTMLInputElement>(null); const [busy,setBusy] = useState(false); const [selected,setSelected] = useState(''); const [pending,setPending] = useState<PreparedReport|null>(null);
  const admin = ctx?.role === 'owner' || ctx?.role === 'manager';
  const {data:imports,isLoading,error} = useQuery({queryKey:['practice-report-imports',ctx?.org_id],enabled:!!ctx&&admin,queryFn:async()=>{
    const {data,error} = await (supabase as any).from('practice_report_imports').select('id,report_start,report_end,payload,imported_at').eq('org_id',ctx!.org_id).order('report_end',{ascending:false});
    if(error) throw error; return data as {id:string;report_start:string;report_end:string;payload:PreparedReport;imported_at:string}[];
  }});
  const active = imports?.find(r=>r.id===selected) ?? imports?.[0]; const p = active?.payload;
  const download = () => {if(!p)return; const url=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'})); const a=document.createElement('a');a.href=url;a.download=`Purple-Envelope-${p.report_start}-${p.report_end}.json`;a.click();URL.revokeObjectURL(url);};
  const upload = async()=>{
    if(!pending||!ctx||!user)return;setBusy(true);
    try {const source_key=`prepared:${pending.report_start}:${pending.report_end}`; const {error}=await (supabase as any).from('practice_report_imports').upsert({org_id:ctx.org_id,source_key,report_start:pending.report_start,report_end:pending.report_end,payload:pending,imported_by:user.id,imported_at:new Date().toISOString()},{onConflict:'org_id,source_key'});if(error)throw error;await qc.invalidateQueries({queryKey:['practice-report-imports']});setPending(null);toast.success('Report history updated.');}catch(e){toast.error(e instanceof Error?e.message:'Report could not be saved.');}finally{setBusy(false);}
  };
  if(ctx&&!admin)return <p className="p-8">Report history is available to practice owners and managers.</p>;
  return <main className="mx-auto max-w-7xl space-y-6 p-4 md:p-8"><header className="flex flex-wrap items-start justify-between gap-4"><div><Link to="/reports" className="text-sm text-primary">Back to Reports</Link><h1 className="mt-2 text-3xl font-bold tracking-tight">Dentrix report history</h1><p className="mt-2 text-muted-foreground">Financial results, reported hours and calendar context from your uploaded reports.</p></div><div className="flex gap-2"><Button variant="outline" onClick={download} disabled={!p}><Download className="mr-2 h-4 w-4"/>Export package</Button><Button onClick={()=>file.current?.click()} disabled={!admin}><FileUp className="mr-2 h-4 w-4"/>Load prepared report</Button></div></header>
  <input ref={file} type="file" accept=".json,application/json" className="hidden" onChange={async e=>{const f=e.target.files?.[0];e.target.value='';if(!f||!ctx)return;try{if(f.size>10*1024*1024)throw new Error('Choose a package smaller than 10 MB.');setPending(validatePreparedReport(JSON.parse(await f.text()),ctx.org_id));}catch(err){toast.error(err instanceof Error?err.message:'Invalid report file.');}}}/>
  <p className="text-xs text-muted-foreground">For another report, provide the PDFs or screenshots to prepare and reconcile a package, then load the JSON here. This updates report history; it does not automatically replace daily closeouts or time-clock records.</p>
  {pending&&<Card className="border-primary"><CardHeader><CardTitle>Ready to load: {pending.report_start} through {pending.report_end}</CardTitle></CardHeader><CardContent className="space-y-3"><p>{pending.daily_financials_by_entry_date.length} financial days · {pending.staff_daily_punches.length} staff days · {money(pending.source_control_totals.recorded_payments_cents)} receipts</p><p className="text-sm">A report with this same date range will be replaced. Other date ranges remain separate and are never added together.</p><Button onClick={upload} disabled={busy}>{busy?'Saving…':'Load this report'}</Button><Button variant="ghost" onClick={()=>setPending(null)}>Cancel</Button></CardContent></Card>}
  {isLoading&&<p>Loading report history…</p>}{error&&<p role="alert">Could not load reports. Please refresh and try again.</p>}
  {!isLoading&&!error&&!p&&<Card><CardContent className="p-8">No prepared reports loaded yet.</CardContent></Card>}
  {p&&<><div className="flex flex-wrap items-center gap-3"><label htmlFor="report-range" className="text-sm font-medium">Report period</label><select id="report-range" className="rounded-md border bg-background p-2 text-sm" value={active?.id} onChange={e=>setSelected(e.target.value)}>{imports?.map(r=><option key={r.id} value={r.id}>{r.report_start} through {r.report_end}</option>)}</select><span className="inline-flex items-center gap-1 text-xs text-muted-foreground"><CheckCircle2 className="h-4 w-4"/>Source totals reconciled</span></div>
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Posted charges',money(p.source_control_totals.posted_charges_cents)],['Receipts',money(p.source_control_totals.recorded_payments_cents)],['Reported staff hours',hours(p.source_control_totals.payroll_reported_minutes)],['New patients of record',String(p.source_control_totals.new_patients_of_record)]].map(([label,value])=><Card key={label}><CardContent className="p-5"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold tabular-nums">{value}</p><p className="mt-1 text-xs text-muted-foreground">Full selected report period</p></CardContent></Card>)}</div>
  <div className="rounded-lg border bg-muted/30 p-4 text-sm"><strong className="flex items-center gap-2"><AlertCircle className="h-4 w-4"/>Read the results accurately</strong><p className="mt-2">June and September are partial months. Charges here use posting dates; the daily dashboard uses procedure dates from the same extract. Receipts can pay older balances and are not a collection rate on this period’s charges. New patients of record are not daily first visits. Cancellations, no-shows, chair utilization and actual payroll cost are not recorded by these reports.</p></div>
  <Tabs defaultValue="overview"><TabsList className="h-auto flex flex-wrap justify-start">{[['overview','Monthly'],['daily','Daily'],['providers','Providers'],['procedures','Procedures'],['receipts','Payment types'],['payroll','Hours & punches'],['rates','Pay rates'],['calendar','Calendar'],['sources','Sources & checks']].map(([v,l])=><TabsTrigger value={v} key={v}>{l}</TabsTrigger>)}</TabsList>
  <TabsContent value="overview" className="space-y-4"><Table rows={p.monthly_financials_by_entry_date} columns={[{key:'month',label:'Month'},{key:'coverage',label:'Coverage'},...financial]}/><p className="text-sm text-muted-foreground">Refunds are already included in charge adjustments; do not add them twice. The office fee comparison difference is {money(p.source_control_totals.office_fee_difference_cents)}, separate from explicit write-off adjustments.</p></TabsContent>
  <TabsContent value="daily"><Table rows={p.daily_financials_by_entry_date} columns={[{key:'date',label:'Posting date'},...financial,{key:'source_pages',label:'Day Sheet pages',format:v=>v?.join(', ')}]}/></TabsContent>
  <TabsContent value="providers" className="space-y-5"><Table rows={p.provider_period_controls} columns={[{key:'provider_code',label:'Code'},{key:'provider_name',label:'Provider'},{key:'posted_charges_cents',label:'Posted charges',format:money},{key:'signed_payments_cents',label:'Allocated receipts',format:v=>money(-v)},{key:'credit_adjustments_cents',label:'Credit adjustments',format:money},{key:'charge_adjustments_cents',label:'Charge adjustments',format:money},{key:'patients_seen',label:'Patients seen'},{key:'new_patients_of_record',label:'New patients of record'}]}/><p className="text-sm text-muted-foreground">Patient counts overlap across providers and must not be summed as unique people.</p><h2 className="text-xl font-semibold">Provider daily detail</h2><Table rows={p.provider_daily_financials_by_entry_date} columns={[{key:'date',label:'Date'},{key:'provider_code',label:'Provider'},...financial]}/></TabsContent>
  <TabsContent value="procedures"><Table rows={p.procedure_monthly_counts_by_entry_date} columns={[{key:'month',label:'Posting month'},{key:'provider_code',label:'Provider'},{key:'code',label:'Code'},{key:'description',label:'Description'},{key:'posted_line_count',label:'Posted lines'},{key:'charge_cents',label:'Charges',format:money}]}/><p className="mt-3 text-sm text-muted-foreground">Posted lines are not unique visits. Broken-appointment fee postings are not a complete count of missed appointments.</p></TabsContent>
  <TabsContent value="receipts" className="space-y-5"><Table rows={p.daily_receipts_by_type} columns={[{key:'date',label:'Date'},{key:'payment_type',label:'Reported payment type'},{key:'amount_cents',label:'Receipts',format:money}]}/><h2 className="text-xl font-semibold">Charges and adjustment types</h2><Table rows={p.transaction_type_totals} columns={[{key:'description',label:'Type'},{key:'classification',label:'Classification'},{key:'row_count',label:'Rows'},{key:'charge_cents',label:'Charge column',format:money},{key:'payment_column_cents',label:'Payment column (signed)',format:money}]}/></TabsContent>
  <TabsContent value="payroll" className="space-y-5"><Table rows={p.staff_reported_hours} columns={[{key:'employee_code',label:'Code'},{key:'name',label:'Employee'},{key:'recorded_hhmm',label:'Reported hours (h:mm)'},{key:'days_in_time_punch_report',label:'Days'},{key:'incomplete_punch_days',label:'Incomplete days'}]}/><p className="text-sm text-muted-foreground">Three incomplete punch rows are flagged below. No missing punch was invented. Reported hours are not paid leave or approved payroll dollars.</p><h2 className="text-xl font-semibold">Daily punches</h2><Table rows={p.staff_daily_punches.map(r=>({...r,name:p.staff_reported_hours.find(s=>s.employee_code===r.employee_code)?.name}))} columns={[{key:'date',label:'Date'},{key:'name',label:'Employee'},{key:'employee_code',label:'Code'},{key:'punches',label:'Punches (Eastern)',format:v=>v.map((x:any,i:number)=>`${i%2?'Out':'In'} ${x.time}${x.edited?' (source edited)':''}`).join(' · ')},{key:'reported_minutes',label:'Reported hours',format:hours},{key:'needs_review',label:'Status',format:v=>v?'Missing punch; review':'Pairs reconcile'},{key:'source_page',label:'Time Punch page'}]}/></TabsContent>
  <TabsContent value="rates" className="space-y-3"><p className="text-sm text-muted-foreground">Screenshot rates have no effective date. Soleil’s rate is missing. Marjorie Vincent’s $35 rate has not been assigned to Megan. Historical payroll cost remains uncalculated.</p><Table rows={p.pay_rates} columns={[{key:'source_name',label:'Name on screenshot'},{key:'payroll_system_id',label:'Payroll ID'},{key:'dentrix_employee_code',label:'Matched Dentrix code'},{key:'hourly_rate_cents',label:'Regular rate',format:money},{key:'overtime_hourly_rate_cents',label:'Overtime rate',format:money},{key:'effective_from',label:'Effective date'}]}/></TabsContent>
  <TabsContent value="calendar" className="space-y-3"><p className="rounded-md bg-muted p-3 text-sm"><strong>OFF = approved absence. OUT = call-out or not approved.</strong> Partial-day wording is retained. Calendar notes do not assign paid leave hours.</p><Table rows={p.calendar_events.map(r=>({...r,status:r.kind==='office_closed'?'Office closed':r.parts?.map((x:any)=>`${x.text}: ${x.status==='approved_absence'?'Approved':x.status==='callout_or_unapproved_absence'?'Call-out / not approved':'Schedule context'}`).join('; ')}))} columns={[{key:'date_start',label:'Start'},{key:'date_end',label:'End'},{key:'label',label:'Original calendar note'},{key:'status',label:'Meaning'},{key:'source',label:'Source'}]}/></TabsContent>
  <TabsContent value="sources" className="space-y-5"><Table rows={p.sources} columns={[{key:'name',label:'Source'},{key:'pages',label:'Pages'},{key:'report_start',label:'From'},{key:'report_end',label:'Through'}]}/><h2 className="text-xl font-semibold">Reconciliation</h2><p className="text-sm">{p.validation.day_sheet_rows?.toLocaleString()} Day Sheet rows and {p.source_control_totals.deposit_items?.toLocaleString()} deposit items are included. Daily, monthly, receipt and employee-hour controls reconciled for this package. Patient names, phone numbers, bank numbers and check numbers are excluded.</p><Table rows={Object.entries(p.definitions).map(([key,value])=>({key,value:typeof value==='string'?value:JSON.stringify(value)}))} columns={[{key:'key',label:'Measure'},{key:'value',label:'Definition'}]}/></TabsContent>
  </Tabs></>}
  </main>;
}
