import { supabase } from '@/integrations/supabase/client';
import type { SupabaseClient } from '@supabase/supabase-js';

/**
 * Typed access to the consent_* tables.
 *
 * The generated Database types in src/integrations/supabase/types.ts are
 * regenerated by Lovable when migrations are applied, so a feature that
 * ships its own migration lags the generator by one cycle. These row types
 * mirror supabase/migrations/20260803230000_consent_forms.sql exactly; the
 * narrow client cast below keeps every consent hook fully typed without
 * hand-editing the generated file. Once the generator catches up the cast
 * is redundant but harmless.
 */

type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type ConsentFormRow = {
  id: string;
  org_id: string;
  name: string;
  category: string;
  status: string;
  procedure_codes: string[];
  editable_by: string;
  requires_patient_signature: boolean;
  requires_doctor_signature: boolean;
  requires_witness_signature: boolean;
  requires_guardian_signature: boolean;
  hygienist_may_complete: boolean;
  includes_cost: boolean;
  is_financial: boolean;
  is_sample: boolean;
  needs_review: boolean;
  source: string;
  current_version: number;
  published_content: Json | null;
  draft_content: Json | null;
  created_by: string | null;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
}

export type ConsentFormVersionRow = {
  id: string;
  org_id: string;
  form_id: string;
  version: number;
  content: Json;
  change_notes: string;
  published_at: string;
  published_by: string | null;
}

export type ConsentBundleRow = {
  id: string;
  org_id: string;
  name: string;
  description: string;
  procedure_codes: string[];
  status: string;
  sort_order: number;
  is_sample: boolean;
  use_count: number;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

export type ConsentBundleItemRow = {
  id: string;
  org_id: string;
  bundle_id: string;
  form_id: string;
  requirement: string;
  condition_label: string;
  sort_order: number;
}

export type ConsentSettingsRow = {
  org_id: string;
  clear_timeout_minutes: number;
  warn_before_clear: boolean;
  team_can_upload: boolean;
  team_can_edit_templates: boolean;
  team_can_publish: boolean;
  team_can_archive: boolean;
  team_can_create_bundles: boolean;
  team_can_override_fees: boolean;
  team_can_print: boolean;
  team_can_change_signatures: boolean;
  require_witness_default: boolean;
  require_guardian_for_minors: boolean;
  financial_form_id: string | null;
  always_offer_financial: boolean;
  updated_by: string | null;
  updated_at: string;
}

export type ConsentAuditRow = {
  id: string;
  org_id: string;
  action: string;
  entity_type: string;
  entity_id: string | null;
  entity_name: string;
  actor_id: string | null;
  actor_name: string;
  detail: Json;
  created_at: string;
}

type Relationship = {
  foreignKeyName: string;
  columns: string[];
  isOneToOne?: boolean;
  referencedRelation: string;
  referencedColumns: string[];
};

type TableShape<Row, Rels extends Relationship[] = []> = {
  Row: Row;
  Insert: Partial<Row>;
  Update: Partial<Row>;
  Relationships: Rels;
};

type ConsentDatabase = {
  public: {
    Tables: {
      consent_forms: TableShape<ConsentFormRow>;
      consent_form_versions: TableShape<ConsentFormVersionRow>;
      consent_bundles: TableShape<ConsentBundleRow>;
      consent_bundle_items: TableShape<
        ConsentBundleItemRow,
        [
          {
            foreignKeyName: 'consent_bundle_items_bundle_id_fkey';
            columns: ['bundle_id'];
            referencedRelation: 'consent_bundles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'consent_bundle_items_form_id_fkey';
            columns: ['form_id'];
            referencedRelation: 'consent_forms';
            referencedColumns: ['id'];
          },
        ]
      >;
      consent_settings: TableShape<ConsentSettingsRow>;
      consent_audit_log: TableShape<ConsentAuditRow>;
    };
    Views: Record<string, never>;
    Functions: {
      consent_bundle_used: {
        Args: { p_bundle_id: string };
        Returns: undefined;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

export const consentDb = supabase as unknown as SupabaseClient<ConsentDatabase>;
