import { supabase } from '@/integrations/supabase/client';
import type { SupabaseClient } from '@supabase/supabase-js';

/**
 * Typed access to the correspondence tables (consents/db.ts pattern).
 *
 * The generated Database types in src/integrations/supabase/types.ts are
 * regenerated by Lovable when migrations are applied, so a feature that
 * ships its own migration lags the generator by one cycle. These row types
 * mirror supabase/migrations/20260807120000_letterhead_correspondence.sql
 * exactly; the narrow client cast keeps every hook fully typed without
 * hand-editing the generated file.
 */

export type LetterTemplateRow = {
  id: string;
  org_id: string;
  title: string;
  category: string;
  subject: string;
  body: string;
  closing: string;
  status: string;
  version: number;
  created_by: string | null;
  updated_by: string | null;
  created_at: string;
  updated_at: string;
};

export type CorrespondenceSettingsRow = {
  org_id: string;
  default_closing: string;
  default_signer_name: string;
  default_signer_title: string;
  school_note_wording: string;
  work_note_wording: string;
  team_can_manage_templates: boolean;
  updated_by: string | null;
  updated_at: string;
};

export type StaffSignatureRow = {
  id: string;
  org_id: string;
  user_id: string;
  storage_path: string;
  allow_office_use: boolean;
  created_at: string;
  updated_at: string;
};

type TableShape<Row> = {
  Row: Row;
  Insert: Partial<Row>;
  Update: Partial<Row>;
  Relationships: [];
};

type LetterDatabase = {
  public: {
    Tables: {
      letter_templates: TableShape<LetterTemplateRow>;
      correspondence_settings: TableShape<CorrespondenceSettingsRow>;
      staff_signatures: TableShape<StaffSignatureRow>;
    };
    Views: Record<string, never>;
    // A concrete entry (not Record<string, never>): under the lockfile's
    // supabase-js the empty-record form degrades maybeSingle() rows to {}.
    Functions: {
      correspondence_team_can: {
        Args: { p_org_id: string };
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export const letterDb = supabase as unknown as SupabaseClient<LetterDatabase>;

/** The private bucket holding staff signature images. */
export const STAFF_SIGNATURES_BUCKET = 'staff-signatures';

/**
 * Canonical storage path for a user's signature. The org/user folder pair is
 * what the storage RLS policies authorize against — self-write only, and
 * teammate reads only behind the owner's allow_office_use flag.
 */
export function staffSignaturePath(orgId: string, userId: string): string {
  return `${orgId}/${userId}/signature.png`;
}
