// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient } from "npm:@supabase/supabase-js@^2.96.0";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Returns the signed-in user's TimeVault identity: email, employee id, org id, org name, and role (owner, manager, or employee).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: membership, error: mErr } = await sb.from("org_members").select("org_id, role").eq("user_id", userId).eq("status", "active").limit(1).maybeSingle();
    if (mErr) return { content: [{ type: "text", text: mErr.message }], isError: true };
    if (!membership) {
      return { content: [{ type: "text", text: "No active org membership found." }], isError: true };
    }
    const { data: employee } = await sb.from("employees").select("id, first_name, last_name, employment_status").eq("org_id", membership.org_id).eq("user_id", userId).maybeSingle();
    const { data: org } = await sb.from("orgs").select("name").eq("id", membership.org_id).maybeSingle();
    const payload = {
      email: ctx.getUserEmail() ?? null,
      user_id: userId,
      employee_id: employee?.id ?? null,
      first_name: employee?.first_name ?? null,
      last_name: employee?.last_name ?? null,
      employment_status: employee?.employment_status ?? null,
      org_id: membership.org_id,
      org_name: org?.name ?? null,
      role: membership.role
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-time-entries.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.96.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_time_entries_default = defineTool2({
  name: "list_time_entries",
  title: "List time entries",
  description: "Lists the signed-in user's own time entries (daily totals) between start_date and end_date (YYYY-MM-DD, inclusive, America/New_York calendar dates). Returns date, total minutes, and total hours.",
  inputSchema: {
    start_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Start date (YYYY-MM-DD), inclusive."),
    end_date: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("End date (YYYY-MM-DD), inclusive.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ start_date, end_date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser2(ctx);
    const { data, error } = await sb.from("time_entries").select("entry_date, total_minutes").gte("entry_date", start_date).lte("entry_date", end_date).order("entry_date", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((r) => ({
      date: r.entry_date,
      total_minutes: r.total_minutes ?? 0,
      total_hours: Number(((r.total_minutes ?? 0) / 60).toFixed(2))
    }));
    const totalMinutes = rows.reduce((s, r) => s + r.total_minutes, 0);
    const payload = {
      start_date,
      end_date,
      count: rows.length,
      total_minutes: totalMinutes,
      total_hours: Number((totalMinutes / 60).toFixed(2)),
      entries: rows
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-pto-requests.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.96.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_pto_requests_default = defineTool3({
  name: "list_pto_requests",
  title: "List PTO requests",
  description: "Lists the signed-in user's own PTO requests, most recent first. Optionally filter by status (pending, approved, denied, canceled).",
  inputSchema: {
    status: z2.enum(["pending", "approved", "denied", "canceled", "any"]).optional().describe("Filter by status. Default 'any'."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = supabaseForUser3(ctx);
    let q = sb.from("pto_requests").select("id, start_date, end_date, hours, status, reason, created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status && status !== "any") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const payload = { count: data?.length ?? 0, requests: data ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lfiplzmxpmybtbzhmnkp";
var mcp_default = defineMcp({
  name: "timevault-mcp",
  title: "TimeVault",
  version: "0.1.0",
  instructions: "Tools for TimeVault, a workforce time tracking app. Use `whoami` to check identity, `list_time_entries` to read the caller's daily hours, and `list_pto_requests` to read their PTO requests. All tools act as the signed-in user; row-level security scopes results to that user's org and employee.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_time_entries_default, list_pto_requests_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
